### ISSUE TITLE
Switch from JavaScript to TypeScript

### ISSUE THREAD

**Issue by johncmanuel** [Google-Developer-Groups-Skyline-College/project.ClubWebsite#4]
While the website is still small, switching from JavaScript to TypeScript would be more valuable in the long run. TypeScript has type checks, which allows TypeScript to catch errors related to the variables' types. Moreover, it would help a ton with debugging errors, since JavaScript would allow the error to occur even if the types are wrong (of course, JavaScript would still catch syntax errors). Switching from JavaScript to TypeScript would therefore inarguably improve the developer experience and benefit everyone working on this project.

**Comment by dev-alto** [comment]
Apologies for missing this issue. I agree that migrating to TypeScript sooner would be more convenient in the long run—especially with the amount of new potential content expected to be added into the new year. Will be adding this as apart of the technology-update branch scope.

**Comment by johncmanuel** [comment]
There is a way to quickly set up a Next.js project in TypeScript, but it does involve restarting the entire project, copy-pasting the JavaScript from the current project, and turning it back into TypeScript. See [`create-next-app`](https://nextjs.org/docs/pages/api-reference/create-next-app).

**Comment by dev-alto** [comment]
Right, that approach is likely the most direct way of migrating over. Making plans to do this immediately after we ship to production our still WIP(although nearly completed) Tailwind-revamped website—which should be done by the weekend.

**Comment by uniploxy** [comment]
Hello, Nearly done with this, just need to make sure the new `next-js-transition` branch works with updated .tsx components.

**Comment by dev-alto** [comment]
This has been completed as of yesterday, expect a PR or straight push to the ~~`technology-update`~~ `next-js-ready` branch. Also likely gonna be  merging said branch to main/production.

**Comment by dev-alto** [comment]
![image](https://github.com/Skyline-College-Computer-Science-Club/project.ClubWebsite/assets/51037255/ddedb61e-0c70-4fde-96e7-fbc339d6d5e4)
